### ISSUE TITLE
Version error

### ISSUE THREAD

**Issue by DavorSaric** [l3dlp/fullsize-ispconfig-theme#1]
Hello,

after enableing the theme and doing logout in ISPconfig, the interface is switched to default theme. The warning is written regading version difference after login in. 

Btw. is this a stable theme and can it be used on production server?

**Comment by l3dlp** [comment]
Hello,

Sorry for the delay, this theme was used on a previous version of ISPConfig.

As I've just switched to the last ISPConfig with Nginx, I'll update it in the following days, and it should stay maintained.

I'll keep you informed. 
And thanks for the feedback!

**Comment by l3dlp** [comment]
_Really sorry for the delay, but my whole house & homework lab has burned in December!!_
_Hard times. I only came back to work these last days._

_Anyway,_ this theme was used on a previous version of ISPConfig.
**The tiny fixes to switch to the last ISPConfig version (3.0.5.4p6) are finally done :)**

You can now consider this theme as stable, 
as next releases will follow ISPConfig timeline as quickly as possible.

Thanks for the feedback!
